# Generated by Django 5.1.1 on 2024-09-17 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed_user_id",
                    models.ManyToManyField(
                        related_name="followers_followed", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "following_user_id",
                    models.ManyToManyField(
                        related_name="followers_following", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
