# Generated by Django 5.1.1 on 2024-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
