# Generated by Django 5.1.1 on 2024-09-18 08:24

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_bio_user_created_at_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.CharField(
                default=user.models.get_random_default_photo, max_length=1000
            ),
        ),
    ]
