# Generated by Django 5.1.1 on 2024-09-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.CharField(
                blank=True,
                default="https://robohash.org/3f705975-412f-48f4-a615-5a5d2fffa8b2.png",
                max_length=1000,
                null=True,
            ),
        ),
    ]
